# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmdoutput.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cmdoutput(object):
    def setupUi(self, Cmdoutput):
        Cmdoutput.setObjectName("Cmdoutput")
        Cmdoutput.resize(456, 265)
        Cmdoutput.setStyleSheet("#Cmdoutput{\n"
"    background-color: qlineargradient(spread:pad, x1:0.233831, y1:0.267, x2:0.831025, y2:0.880364, stop:0 rgba(245,247,250,1), stop:1 rgba(195,207,226));\n"
"}")
        self.Cmd = TextEdit(Cmdoutput)
        self.Cmd.setGeometry(QtCore.QRect(28, 60, 401, 176))
        self.Cmd.setReadOnly(False)
        self.Cmd.setMarkdown("")
        self.Cmd.setObjectName("Cmd")
        self.currentNumLabel = StrongBodyLabel(Cmdoutput)
        self.currentNumLabel.setGeometry(QtCore.QRect(290, 30, 131, 20))
        self.currentNumLabel.setObjectName("currentNumLabel")

        self.retranslateUi(Cmdoutput)
        QtCore.QMetaObject.connectSlotsByName(Cmdoutput)

    def retranslateUi(self, Cmdoutput):
        _translate = QtCore.QCoreApplication.translate
        Cmdoutput.setWindowTitle(_translate("Cmdoutput", "Form"))
        self.currentNumLabel.setText(_translate("Cmdoutput", "🎮当前进行第0局"))
from qfluentwidgets import StrongBodyLabel, TextEdit
